[build]
  # Process any remaining files with question marks (though you should run rename-files.sh locally first)
  command = "bash ./netlify-build.sh"
  # Publish from the root directory
  publish = "."

# Handle 404 errors by redirecting to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle WordPress page URLs with query parameters
[[redirects]]
  from = "/index.html?p=:id"
  to = "/page-:id.html"
  status = 301
  force = true

[[redirects]]
  from = "/index.html?p=:id.html"
  to = "/page-:id.html"
  status = 301
  force = true

# Set cache headers for static assets
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/wp-content/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/wp-includes/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"